library("data.table", lib.loc="~/R/win-library/3.5")
twodays<-fread(input='household_power_consumption.txt',sep=';',nrows=2880,header=FALSE,na.strings='?',skip=66637)
head(twodays)
tail(twodays)
columns=c('Date','Time','Global_active_power','Global_reactive_power','Voltage','Global_intensity','Sub_metering_1','Sub_metering_2','Sub_metering_3')
colnames(twodays)<-columns
library("lubridate", lib.loc="~/R/win-library/3.5")
twodays$datetime<-dmy_hms(twodays$datetime)
head(twodays)
class(twodays$datetime)
par(mfcol=c(2,2),mar=c(4,4,4,4))
plot(twodays$datetime,twodays$Global_active_power,type='l',main='',xlab='',ylab='Global Active Power (kilowatts)')
plot(twodays$datetime,twodays$Sub_metering_1,xlab='',ylab='Energy Sub Metering',type='l')
lines(twodays$datetime,twodays$Sub_metering_2,col='red')
lines(twodays$datetime,twodays$Sub_metering_3,col='blue')
leg<-c('Sub_metering_1','Sub_metering_2','Sub_metering_3')
legend('topright',legend=leg,lty=c(1,1,1),col=c('black','red','blue'),bty='n',cex=0.7)
plot(twodays$datetime,twodays$Voltage,type='l',main='',xlab='datetime',ylab='Voltage')
plot(twodays$datetime,twodays$Global_reactive_power,type='l',main='',xlab='datetime',ylab='Global_reactive_power')
dev.copy(png,'plot4.png')
dev.off()